### ISSUE TITLE
V2 doesn't work

### ISSUE THREAD

**Issue by TechStudent10** [KendallDoesCoding/typinggame#1]
Observe the screenshot below:

![image](https://user-images.githubusercontent.com/76978184/219394257-c97f0657-d9a8-4daf-b025-6a2d460df270.png)

**Comment by KendallDoesCoding** [comment]
@TechStudent10 , You must type the words that it shows on the screen, in the proper capitalization (here, you typed everything in the UPPERCASE capitalization and I don't think you typed the words on the screen, you typed what you felt like.. It's a game..)

**Comment by TechStudent10** [comment]
Should probably clarify that.

**Comment by KendallDoesCoding** [comment]
If you got the answers correct, where the words display (are visible in your screenshot), they will be green. I played the game and got my WPM showing as a number when the game was done.. 

I request you to screen-record you playing the game and upload it here, so we can determine the issue.

**Comment by TechStudent10** [comment]
> If you got the answers correct, where the words display (are visible in your screenshot), they will be green. I played the game and got my WPM showing as a number when the game was done..
> 
> I request you to screen-record you playing the game and upload it here, so we can determine the issue.

You already said that? I was asking you to add some text on the page saying that it's case-sensitive.

**Comment by KendallDoesCoding** [comment]
> > If you got the answers correct, where the words display (are visible in your screenshot), they will be green. I played the game and got my WPM showing as a number when the game was done..
> > I request you to screen-record you playing the game and upload it here, so we can determine the issue.
> 
> You already said that? I was asking you to add some text on the page saying that it's case-sensitive.

Oh okay, but did you type the words as per displayed on the screen?

**Comment by TechStudent10** [comment]
Yes

**Comment by KendallDoesCoding** [comment]
Ok! Will add text on the website saying it's text sensitive.
